{% set cpan_name = "Number-Format" %}
{% set version = "1.76" %}
{% set sha256 = "0e0060eb363635a885706c6a26f5fcaafeae759f7b2acae49dda70e195dd44d6" %}

package:
  name: perl-{{ cpan_name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Number-Format-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Number::Format

about:
  home: https://metacpan.org/pod/Number::Format
  summary: Perl extension for formatting numbers
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvolkening
